services:
  traefik:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      # The HTTPS port
      - "443:443"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock # For Windows with Docker Desktop
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - ./data/certs/:/var/traefik/certs/:rw
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.ccweerasinghe.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - proxy  
networks:
  proxy:
    external: true

