services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    command: --api.insecure=true --providers.docker=true
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yaml
      - ./data/certs/:/var/traefik/certs/:rw
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.ccweerasinghe.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - proxy  
networks:
  proxy:
    external: true

